# Generated by Django 5.0.3 on 2024-08-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Enter_Your_Id',
        ),
        migrations.AlterField(
            model_name='data',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='Password',
            field=models.CharField(max_length=123),
        ),
    ]
